- platform: command_line
  name: CPU Temperature
  command: >-
    echo "scale=1; $(cat /sys/class/thermal/thermal_zone0/temp)/1000" | bc
  unit_of_measurement: "°C"

- platform: command_line
  name: GPU Temperature
  command: >-
    echo $(/opt/vc/bin/vcgencmd measure_temp) | sed 's/[^0-9\.]//g'
  unit_of_measurement: "°C"

- platform: command_line
  name: Ping Aliyun
  command: >-
    ping -c 10 47.75.80.159 | grep 'packet loss' | sed "s/.*received, //g" | sed "s/%.*$//g"
  scan_interval: 60
  timeout: 00:01:00
  unit_of_measurement: "%"

- platform: command_line
  name: Ping BanwagonHost
  command: >-
    ping -c 10 67.230.181.57 | grep 'packet loss' | sed "s/.*received, //g" | sed "s/%.*$//g"
  scan_interval: 60
  timeout: 00:01:00
  unit_of_measurement: "%"

- platform: systemmonitor
  resources:
    - type: load_1m
    - type: memory_free
    - type: disk_use_percent
      arg: /
    - type: last_boot
