- platform: moji_weather
  name: Moji Weather
  monitored_conditions:
    - weather
    - weather_current
    - weather_tips
    - temperature
    - temp_min
    - temp_max
    - wind_grade
    - air_quality
    - humidity
  scan_interval: 1800

# 空气质量
- platform: waqi
  token: !secret sensor_weather_waqi_token
  locations:
    - shanghai
  scan_interval: 1800