- alias: 'Notify open the door more than 5 minutes'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00020e37c8
      to: 'on'
      for: '00:01:00'

  condition:
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d00023d15d6
      state: 'off'

  action:
    - service: notify.ios_lukiniphone
      data_template:
        message: >-
          大门超过{{ (states.binary_sensor.door_window_sensor_158d00020e37c8.attributes['Open since'] | int / 60) | round }}分钟未关闭
