- alias: 'Notify Weather Workday'
  initial_state: true
  trigger:
    - platform: time
      at: '06:55:00'

  condition:
    # 工作日
    - condition: state
      entity_id: sensor.chinese_calendar
      state: 'workday'

  action:

    - service: script.set_vlc_volume
      data:
        value: 0.8

    - service: tts.baidu_say
      data_template:
        entity_id: media_player.speaker_vlc
        message: >-
          {%- for num in range(0,2) -%}
            今天天气{{ states('sensor.moji_weather_condition') }}，当前气温
            {{- states('sensor.moji_weather_temperature') }}度，当前天气
            {{- states('sensor.moji_weather_current') }}，最高
            {{- states('sensor.moji_weather_temperature_max') }}度，最低
            {{- states('sensor.moji_weather_temperature_min') }}度，
            {{- states('sensor.moji_weather_tips') -}}
            空气质量：
            {%- if states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 50 -%}
            优
            {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 100 -%}
            良
            {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 150 -%}
            轻度污染
            {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 200 -%}
            中度污染
            {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 300 -%}
            重度污染
            {%- else -%}
            严重污染
            {% endif -%}

            {%- if not loop.last -%}
            ，
            {%- endif -%}
          {% endfor -%}

    - delay: 00:00:05
    - wait_template: >-
        {{ not is_state('media_player.speaker_vlc', 'playing') }}

    # 恢复播放器的音量
    - service: script.set_volume_to_pre


- alias: 'Notify Weather Holiday'
  initial_state: true
  trigger:
    - platform: time
      at: '08:50:00'

  condition:
    # 节假日
    - condition: state
      entity_id: sensor.chinese_calendar
      state: 'holiday'

  action:

    - service: script.set_vlc_volume
      data:
        value: 0.8

    - service: tts.baidu_say
      data_template:
        entity_id: media_player.speaker_vlc
        message: >-
          {%- for num in range(0,2) -%}
            今天天气{{ states('sensor.moji_weather_condition') }}，当前气温
            {{- states('sensor.moji_weather_temperature') }}度，当前天气
            {{- states('sensor.moji_weather_current') }}，最高
            {{- states('sensor.moji_weather_temperature_max') }}度，最低
            {{- states('sensor.moji_weather_temperature_min') }}度，
            {{- states('sensor.moji_weather_tips') -}}
            空气质量：
            {%- if states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 50 -%}
            优
            {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 100 -%}
            良
            {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 150 -%}
            轻度污染
            {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 200 -%}
            中度污染
            {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 300 -%}
            重度污染
            {%- else -%}
            严重污染
            {% endif -%}

            {%- if not loop.last -%}
            ，
            {%- endif -%}
          {% endfor -%}

    - delay: 00:00:05
    - wait_template: >-
        {{ not is_state('media_player.speaker_vlc', 'playing') }}

    # 恢复播放器的音量
    - service: script.set_volume_to_pre

