- alias: 'Notify Luvis for wake up'
  trigger:
    - platform: time
      at: '06:50:00'

  condition:
    condition: and
    conditions:
      # 工作日
      - condition: state
        entity_id: sensor.chinese_calendar
        state: 'workday'

      # 非暑假
      - condition: template
        value_template: >-
          {% set holiday_start = as_timestamp('{}-07-01 00:00:00'.format(now().year)) %}
          {% set holiday_end = as_timestamp('{}-09-01 00:00:00'.format(now().year)) %}
          {% set current_time = as_timestamp(now()) %}

          {%- if holiday_start <= current_time and current_time < holiday_end -%}
          false
          {%- else -%}
          true
          {%- endif -%}


  action:
    - service: script.set_vlc_volume
      data:
        value: 0.9

    - service: tts.baidu_say
      data_template:
        entity_id: media_player.speaker_vlc
        message: >-
          {%- for num in range(0,3) -%}
            {{ [
              "卢维斯，起床啦！",
              "卢维斯，起床啦！起床啦！起床啦！",
              "卢维斯，太阳晒屁股了，赶紧起床啦！",
              "卢维斯，再不起床就要迟到了！"
            ] | random }}

            {%- if not loop.last -%}
            ，
            {%- endif -%}
          {% endfor -%}

    - delay: 00:00:05
    - wait_template: >-
        {{ not is_state('media_player.speaker_vlc', 'playing') }}

    # 恢复播放器的音量
    - service: script.set_volume_to_pre

- alias: 'Notify Luvis for to school'
  trigger:
    - platform: time
      at: '07:45:00'

  condition:
    condition: and
    conditions:
      # 工作日
      - condition: state
        entity_id: sensor.chinese_calendar
        state: 'workday'

      # 非暑假
      - condition: template
        value_template: >-
          {% set holiday_start = as_timestamp('{}-07-01 00:00:00'.format(now().year)) %}
          {% set holiday_end = as_timestamp('{}-09-01 00:00:00'.format(now().year)) %}
          {% set current_time = as_timestamp(now()) %}

          {%- if holiday_start <= current_time and current_time < holiday_end -%}
          false
          {%- else -%}
          true
          {%- endif -%}

  action:
    - service: script.set_vlc_volume
      data:
        value: 0.9

    - service: tts.baidu_say
      data_template:
        entity_id: media_player.speaker_vlc
        message: >-
          {{ [
            "卢维斯，收拾好书包，要去上学校了！",
            "卢先生，别看手机啦！快去送卢维斯上学啦！",
            "太阳当空照，花儿对我笑，小鸟说，早早早，我要背上炸药包，我去炸学校，从来不迟到！",
            "太阳当空照，花儿对我笑，小鸟说，早早早，我要背上小书包，我去上学校，从来不迟到！",
          ] | random -}}
          今天空气质量：
          {%- if states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 50 -%}
          优，出门不用戴口罩。
          {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 100 -%}
          良，出门不用戴口罩。
          {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 150 -%}
          轻度污染，要想活的久，带上口罩吧！
          {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 200 -%}
          中度污染，要想活的久，带上口罩吧！
          {%- elif states('sensor.waqi_huangpu_ruijin_shanghai') | int <= 300 -%}
          重度污染，警告！警告！警告！不带口罩真的会出人命的！
          {%- else -%}
          严重污染，警告！警告！警告！必须带上口罩！必须带上口罩！必须带上口罩！
          {% endif -%}

    - delay: 00:00:05
    - wait_template: >-
        {{ not is_state('media_player.speaker_vlc', 'playing') }}

    # 恢复播放器的音量
    - service: script.set_volume_to_pre
