- alias: 'Restart Router'
  initial_state: true
  trigger:
    - platform: time
      at: '02:30:00'

  condition:
    condition: time
    weekday:
      - mon

  action:
    - service: shell_command.restart_f450g_router

